name: Rust

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: taiki-e/install-action@cargo-llvm-cov

            - name: Install Stable Toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1

            - name: Run Cargo Test
              run: cargo llvm-cov --all-features --lcov --output-path lcov.info

            - name: Upload Coverage to Codecov
              uses: Wandalen/wretry.action@v1
              with:
                  action: codecov/codecov-action@v4
                  attempt_limit: 3
                  attempt_delay: 10000
                  with: |
                      token: ${{ secrets.CODECOV_TOKEN }}
                      files: lcov.info
                      fail_ci_if_error: true
